server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never

spring:
  r2dbc:
    url: r2dbc:h2:mem:///wms_db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    
---

spring:
  config:
    activate:
      on-profile:
      - prod
  r2dbc:
    url: r2dbc:h2:file:///~//wms_db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
